### ISSUE TITLE
ofx importer assumes one org per file

### ISSUE THREAD

**Issue by carljm** [jbms/beancount-import#11]
ofxclient has a "combined download" option where it downloads all your accounts into a single OFX file. This is pretty convenient if you have a lot of accounts, compared to one by one downloading them.

But the ofx importer in beancount-import can't handle transactions from multiple orgs in a single file, due to the code here: https://github.com/jbms/beancount-import/blob/master/beancount_import/source/ofx.py#L1133

It just looks for the first ORG element and then assumes that is the correct org for all transactions in the file.

Seems like fixing this might require a more sophisticated parsing of the OFX file format, looking at nesting etc, rather than just "find org" and then "find all transactions."

**Comment by jbms** [comment]
Looking at the ofxclient code, I see that it just concatenates the contents of the top-level OFX tags from each file into a single file to produce the "combined" download.

If you look at this example file:

https://github.com/jbms/beancount-import/blob/master/testdata/source/ofx/vanguard_roth_ira.ofx

you can see that the structure is:
```
<OFX>
  <SIGNONMSGSRSV1>
    <SONRS>
      <FI>
        <ORG>MyBank
        <FID>89449
      </FI>
    </SONRS>
  </SIGNONMSGSRSV1>
  <INVSTMTMSGSRSV1>
    ...
  </INVSTMTMSGSRSV1>
  <SECLISTMSGSRSV1>
    <SECLIST>
     ...
    </SECLIST>
  </SECLISTMSGSRSV1>
</OFX>
```

Therefore if you concatenate multiple files you will end up with a structure like:

```
<OFX>
  <SIGNONMSGSRSV1>
    <SONRS>
      <FI>
        <ORG>MyBank
        <FID>89449
      </FI>
    </SONRS>
  </SIGNONMSGSRSV1>
  <INVSTMTMSGSRSV1>
    ...
  </INVSTMTMSGSRSV1>
  <SECLISTMSGSRSV1>
    <SECLIST>
     ...
    </SECLIST>
  </SECLISTMSGSRSV1>
  <SIGNONMSGSRSV1>
    <SONRS>
      <FI>
        <ORG>MyOtherBank
        <FID>12345
      </FI>
    </SONRS>
  </SIGNONMSGSRSV1>
  <INVSTMTMSGSRSV1>
    ...
  </INVSTMTMSGSRSV1>
  <SECLISTMSGSRSV1>
    <SECLIST>
     ...
    </SECLIST>
  </SECLISTMSGSRSV1>
</OFX>
```

While this could be supported, I don't think concatenating files like this is valid according to the OFX spec.  I believe there is supposed to be exactly one  <SIGNONMSGSRSV1> or similar tag that applies to the entire file.

Also, since these files serve as your permanent record of your account data, I think it would generally be inconvenient to have multiple accounts, and multiple banks, all combined into the same files.

Regarding convenience of downloading, have you looked at finance-dl (https://github.com/jbms/finance-dl)?  The ofx module of finance-dl is an automation layer on top of the ofxclient package that handles downloading in a more automatic fashion, which I expect you may find even more convenient than the combined download option of ofxclient.

**Comment by carljm** [comment]
Thanks for the thorough response! I haven't looked at what's valid per OFX spec, you might be right. I'll take a look at finance-dl. Feel free to close this issue if you don't think it should be supported in beancount-import.

Thanks for the excellent project!
