### ISSUE TITLE
Generic CSV importer

### ISSUE THREAD

**Issue by TiraelSedai** [jbms/beancount-import#18]
Hi. I've recently opened an account in a bank that doesn't support OFX export.

I'd like to write a general CSV importer, but I'm having a hard time even starting. Where do I look? I found venmo.py Is probably closest to just CSV, but it's still a bit of a stretch to cut it back to my needs.

CSV structure looks sufficient to uniquely match transaction and have a description and whatnot:

`Account type; Account number; Currency; Date (dd.mm.yyyy); Reference; Description; Credit; Debit`

Reference is somewhat unique and looks like this:

CRD_3629XM - operation with card

A102705190005380 - operation with account

HOLD - you guessed it

Obviously as a lazy person I'd like to just have a working solution in some next release, but steering me in the direction on how to write it myself would be nice too.

**Comment by jbms** [comment]
If you write a generic CSV importer that would be really awesome!

You may want to look at the beancount.ingest.importers.csv module for some inspiration, or perhaps try to even be somehow compatible with importers written for that module --- though I don't have any experience with it so I'm not sure how well it fits the beancount-import model.

The venmo datasource does unfortunately have some added complexity to deal with the transfer transactions.

I think the best starting point would be mint.py, since mint is also CSV-based.  The main difference is that mint does not provide any unique transaction id, so it has to rely on other fields to identify the transaction.  Since you have a unique id, you can do better.  It also supports multiple accounts, while your CSV files may only contain data for a single account.  When generating the transactions, I'd recommend you put the description as the source_desc posting metadata field and the reference as something like csv_reference.  Assuming HOLD refers to a pending hold, I recommend that you ignore it.

**Comment by TiraelSedai** [comment]
I just want to give a heads up that I didn't end up writing a plugin and I'm using https://github.com/kedder/ofxstatement instead to convert my bank's csv to an OFX.
There is a weird thing tho, and I am need @jbms you to take a look when you have time.

ofxstatement produces this thing at the end of ofx:
`
        <LEDGERBAL>
          <BALAMT/>
          <DTASOF/>
        </LEDGERBAL>
`
Because CSV doesn't have any info about balance at the end whatsoever. However, beancount-import crashes with exception when sees empty <DTASOF/> tag. When I remove the block (its useless anyway) everything works fine.

Can you check for me if the empty block that ofxstatement produces is legit ofx format and if so, fix the exception? Otherwise I'd go and submit an issue to the my bank's plugin so that they won't produce that block.

**Comment by jbms** [comment]
It looks like according to the OFX spec 2.2
https://www.ofx.net/downloads/OFX%202.2.pdf
(pdf page 94) for amount,
(pdf page 218) for STMTRS,

all of those fields are required, but DTASOF and BALAMT should also have valid values.

Since there is no balance information available, though, it is impossible for ofxstatement to comply with the spec.
