### ISSUE TITLE
[Feature Request] Add Support for open banking aggregator GoCardless

### ISSUE THREAD

**Issue by dev590t** [jbms/beancount-import#240]
The open-source accounting software Firefly III already integrates with some free open banking APIs. For more information, you can visit the [Firefly III Documentation](https://docs.firefly-iii.org/how-to/data-importer/import/gocardless/).

GoCardless supports many PSD2-compliant banks in the EU and the UK, and it is free to use. It supports [over 2500 banks](https://gocardless.com/bank-account-data/coverage/), covering most of the currently supported data sources by `beancount-import`.

Adding support for GoCardless would be a great enhancement.

**Comment by Zburatorul** [comment]
Downloading the data is out of scope for this project. That would be finance_dl.

**Comment by carposio** [comment]
tariochbctools also includes an importer for Nordigen (which is the former name of the banking api provider of GoCardless):

Github: https://github.com/tarioch/beancounttools
Docs: https://tariochbctools.readthedocs.io/en/latest/importers.html#nordigen

**Comment by dev590t** [comment]
@carposio that is perfect!

**Comment by john-frandsen** [comment]
Disclosure: I'm affiliated with open-banking.io. For anyone landing here still wanting EU/UK open-banking data in a plaintext ledger — since GoCardless/Nordigen closed new personal accounts and rate-limits to 4 req/account/day — there's now a beangulp importer that uses open-banking.io as the source (client-side decryption, no eIDAS certificate, no daily rate-limit wall): https://github.com/open-banking-io/clients/tree/main/beancount
