### ISSUE TITLE
Updating schwab_csv.py with BankingEntryTypes "DEPOSIT"

### ISSUE THREAD

**Issue by chandler150** [jbms/beancount-import#99]
line 150 of /sources/schwab_csv.py

class BankingEntryType(enum.Enum):
    DEPOSIT = "DEPOSIT"
    ACH = "ACH"
    INTADJUST = "INTADJUST"
    TRANSFER = "TRANSFER"
    VISA = "VISA"
    ATM = "ATM"
    CHECK = "CHECK"

**Comment by Zburatorul** [comment]
@chandler150 can you provide a sample line from the transactions file that involves DEPOSIT?

**Comment by Zburatorul** [comment]
Bump.

**Comment by carljm** [comment]
Hi @chandler150, we need to not only add `DEPOSIT` to `BankingEntryType` but it needs to be handled correctly in later stages as well; in order to be sure we are doing that correctly we need to see a sample `DEPOSIT` line (you can of course change any details or amounts to anonymize the transaction) that we can add to the test suite. If you or anyone else can provide that here, we can add support.

**Comment by cjasmith** [comment]
Here is a sample line. 

```csv
Transactions  for Checking account XXXXXX-123456 as of 11/17/2021 20:27:00 ET From 11/01/2021 to 11/17/2021
"Date","Type","Check #","Description","Withdrawal (-)","Deposit (+)","RunningBalance"
"Pending Transactions are not reflected within this sort criterion."
"Posted Transactions"
"11/01/2021","DEPOSIT","","Deposit Mobile Banking","","$1,234.56","$7,890.00"
```

**Comment by cjasmith** [comment]
As a workaround I have changed `DEPOSIT` to `CHECK`.

**Comment by Zburatorul** [comment]
Thank you @cjasmith, I used your sample in the PR.
